// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/members': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/members.post').default>>>>
    }
    '/api/shuttlecock/add-player': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shuttlecock/add-player.post').default>>>>
    }
    '/api/shuttlecock/remove-player': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shuttlecock/remove-player.post').default>>>>
    }
    '/api/shuttlecock/toggle-payment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shuttlecock/toggle-payment.post').default>>>>
    }
    '/api/shuttlecock/update-fee': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shuttlecock/update-fee.post').default>>>>
    }
    '/api/tubes': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tubes.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tubes.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/tubes.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}